const GM_NAME_BY_NOTE = new Map([
  [35, "Acoustic Bass Drum"],
  [36, "Bass Drum 1"],
  [37, "Side Stick"],
  [38, "Acoustic Snare"],
  [39, "Hand Clap"],
  [40, "Electric Snare"],
  [41, "Low Floor Tom"],
  [42, "Closed Hi-Hat"],
  [43, "High Floor Tom"],
  [44, "Pedal Hi-Hat"],
  [45, "Low Tom"],
  [46, "Open Hi-Hat"],
  [47, "Low-Mid Tom"],
  [48, "Hi-Mid Tom"],
  [49, "Crash Cymbal 1"],
  [50, "High Tom"],
  [51, "Ride Cymbal 1"],
  [52, "Chinese Cymbal"],
  [53, "Ride Bell"],
  [54, "Tambourine"],
  [55, "Splash Cymbal"],
  [56, "Cowbell"],
  [57, "Crash Cymbal 2"],
  [58, "Vibraslap"],
  [59, "Ride Cymbal 2"],
  [60, "Hi Bongo"],
  [61, "Low Bongo"],
  [62, "Mute Hi Conga"],
  [63, "Open Hi Conga"],
  [64, "Low Conga"],
  [65, "High Timbale"],
  [66, "Low Timbale"],
  [67, "High Agogo"],
  [68, "Low Agogo"],
  [69, "Cabasa"],
  [70, "Maracas"],
  [71, "Short Whistle"],
  [72, "Long Whistle"],
  [73, "Short Guiro"],
  [74, "Long Guiro"],
  [75, "Claves"],
  [76, "Hi Wood Block"],
  [77, "Low Wood Block"],
  [78, "Mute Cuica"],
  [79, "Open Cuica"],
  [80, "Mute Triangle"],
  [81, "Open Triangle"],
]);

export const GM_INSTRUMENT_NAMES = [
  "acoustic_grand_piano",
  "bright_acoustic_piano",
  "electric_grand_piano",
  "honkytonk_piano",
  "electric_piano_1",
  "electric_piano_2",
  "harpsichord",
  "clavinet",
  "celesta",
  "glockenspiel",
  "music_box",
  "vibraphone",
  "marimba",
  "xylophone",
  "tubular_bells",
  "dulcimer",
  "drawbar_organ",
  "percussive_organ",
  "rock_organ",
  "church_organ",
  "reed_organ",
  "accordion",
  "harmonica",
  "tango_accordion",
  "acoustic_guitar_nylon",
  "acoustic_guitar_steel",
  "electric_guitar_jazz",
  "electric_guitar_clean",
  "electric_guitar_muted",
  "overdriven_guitar",
  "distortion_guitar",
  "guitar_harmonics",
  "acoustic_bass",
  "electric_bass_finger",
  "electric_bass_pick",
  "fretless_bass",
  "slap_bass_1",
  "slap_bass_2",
  "synth_bass_1",
  "synth_bass_2",
  "violin",
  "viola",
  "cello",
  "contrabass",
  "tremolo_strings",
  "pizzicato_strings",
  "orchestral_harp",
  "timpani",
  "string_ensemble_1",
  "string_ensemble_2",
  "synth_strings_1",
  "synth_strings_2",
  "choir_aahs",
  "voice_oohs",
  "synth_choir",
  "orchestra_hit",
  "trumpet",
  "trombone",
  "tuba",
  "muted_trumpet",
  "french_horn",
  "brass_section",
  "synth_brass_1",
  "synth_brass_2",
  "soprano_sax",
  "alto_sax",
  "tenor_sax",
  "baritone_sax",
  "oboe",
  "english_horn",
  "bassoon",
  "clarinet",
  "piccolo",
  "flute",
  "recorder",
  "pan_flute",
  "blown_bottle",
  "shakuhachi",
  "whistle",
  "ocarina",
  "lead_1_square",
  "lead_2_sawtooth",
  "lead_3_calliope",
  "lead_4_chiff",
  "lead_5_charang",
  "lead_6_voice",
  "lead_7_fifths",
  "lead_8_bass_lead",
  "pad_1_new_age",
  "pad_2_warm",
  "pad_3_polysynth",
  "pad_4_choir",
  "pad_5_bowed",
  "pad_6_metallic",
  "pad_7_halo",
  "pad_8_sweep",
  "fx_1_rain",
  "fx_2_soundtrack",
  "fx_3_crystal",
  "fx_4_atmosphere",
  "fx_5_brightness",
  "fx_6_goblins",
  "fx_7_echoes",
  "fx_8_scifi",
  "sitar",
  "banjo",
  "shamisen",
  "koto",
  "kalimba",
  "bagpipe",
  "fiddle",
  "shanai",
  "tinkle_bell",
  "agogo",
  "steel_drums",
  "woodblock",
  "taiko_drum",
  "melodic_tom",
  "synth_drum",
  "reverse_cymbal",
  "guitar_fret_noise",
  "breath_noise",
  "seashore",
  "bird_tweet",
  "telephone_ring",
  "helicopter",
  "applause",
  "gunshot",
];

const AUTO_ZONE_BY_NOTE = new Map([
  [35, "bass"],
  [36, "bass"],
  [37, "tom3"],
  [38, "tom3"],
  [39, "tom3"],
  [40, "tom3"],
  [41, "tom1"],
  [42, "cymbalRod"],
  [43, "tom5"],
  [44, "cymbalRod"],
  [45, "tom2"],
  [46, "cymbalRod"],
  [47, "tom4"],
  [48, "tom4"],
  [49, "cymbalRod"],
  [50, "tom3"],
  [51, "cymbalRod"],
  [52, "cymbalRod"],
  [53, "cymbalRod"],
  [54, "cymbalRod"],
  [55, "cymbalRod"],
  [56, "cymbalRod"],
  [57, "cymbalRod"],
  [58, "cymbalRod"],
  [59, "cymbalRod"],
  [60, "tom3"],
  [61, "tom1"],
  [62, "tom4"],
  [63, "tom4"],
  [64, "tom2"],
  [65, "tom3"],
  [66, "tom5"],
  [67, "tom4"],
  [68, "tom2"],
  [69, "cymbalRod"],
  [70, "cymbalRod"],
  [71, "cymbalRod"],
  [72, "cymbalRod"],
  [73, "cymbalRod"],
  [74, "cymbalRod"],
  [75, "tom3"],
  [76, "tom3"],
  [77, "tom1"],
  [78, "tom5"],
  [79, "tom1"],
  [80, "cymbalRod"],
  [81, "cymbalRod"],
]);

export const ZONES = [
  { id: "tom1", label: "Tom 1" },
  { id: "tom2", label: "Tom 2" },
  { id: "tom3", label: "Tom 3" },
  { id: "tom4", label: "Tom 4" },
  { id: "tom5", label: "Tom 5" },
  { id: "cymbalRod", label: "Cymbal" },
  { id: "bass", label: "Bass Drum" },
];

const FAMILY_PATCHES = {
  piano: {
    wave: "triangle",
    sub: "sine",
    subRatio: 0.3,
    attack: 0.006,
    decay: 0.08,
    sustainRatio: 0.4,
    release: 0.2,
    filter: 3400,
  },
  chromatic: {
    wave: "triangle",
    sub: "sine",
    subRatio: 0.35,
    attack: 0.004,
    decay: 0.05,
    sustainRatio: 0.3,
    release: 0.15,
    filter: 4200,
  },
  organ: {
    wave: "square",
    sub: "sine",
    subRatio: 0.45,
    attack: 0.012,
    decay: 0.02,
    sustainRatio: 0.95,
    release: 0.04,
    filter: 3800,
  },
  guitar: {
    wave: "sawtooth",
    sub: "triangle",
    subRatio: 0.2,
    attack: 0.004,
    decay: 0.1,
    sustainRatio: 0.3,
    release: 0.15,
    filter: 2600,
  },
  bass: {
    wave: "sine",
    sub: "triangle",
    subRatio: 0.55,
    attack: 0.005,
    decay: 0.05,
    sustainRatio: 0.8,
    release: 0.2,
    filter: 1100,
  },
  strings: {
    wave: "sawtooth",
    sub: "sawtooth",
    subRatio: 0.5,
    attack: 0.09,
    decay: 0.15,
    sustainRatio: 0.85,
    release: 0.35,
    filter: 2800,
  },
  ensemble: {
    wave: "sawtooth",
    sub: "square",
    subRatio: 0.4,
    attack: 0.11,
    decay: 0.15,
    sustainRatio: 0.85,
    release: 0.35,
    filter: 2600,
  },
  brass: {
    wave: "sawtooth",
    sub: "square",
    subRatio: 0.3,
    attack: 0.045,
    decay: 0.1,
    sustainRatio: 0.8,
    release: 0.15,
    filter: 3600,
  },
  reed: {
    wave: "sawtooth",
    sub: "sine",
    subRatio: 0.3,
    attack: 0.035,
    decay: 0.08,
    sustainRatio: 0.78,
    release: 0.15,
    filter: 2400,
  },
  pipe: {
    wave: "sine",
    sub: "triangle",
    subRatio: 0.25,
    attack: 0.03,
    decay: 0.05,
    sustainRatio: 0.75,
    release: 0.2,
    filter: 4200,
  },
  lead: {
    wave: "square",
    sub: "sawtooth",
    subRatio: 0.25,
    attack: 0.005,
    decay: 0.04,
    sustainRatio: 0.7,
    release: 0.12,
    filter: 4600,
  },
  pad: {
    wave: "sawtooth",
    sub: "sine",
    subRatio: 0.4,
    attack: 0.18,
    decay: 0.2,
    sustainRatio: 0.9,
    release: 0.45,
    filter: 2200,
  },
  other: {
    wave: "triangle",
    sub: "sine",
    subRatio: 0.3,
    attack: 0.008,
    decay: 0.06,
    sustainRatio: 0.55,
    release: 0.15,
    filter: 3200,
  },
};

function melodicFamily(program) {
  const p = program || 0;
  if (p <= 7) return "piano";
  if (p <= 15) return "chromatic";
  if (p <= 23) return "organ";
  if (p <= 31) return "guitar";
  if (p <= 39) return "bass";
  if (p <= 47) return "strings";
  if (p <= 55) return "ensemble";
  if (p <= 63) return "brass";
  if (p <= 71) return "reed";
  if (p <= 79) return "pipe";
  if (p <= 87) return "lead";
  if (p <= 95) return "pad";
  return "other";
}

export function familyPatchFor(program) {
  return FAMILY_PATCHES[melodicFamily(program)] || FAMILY_PATCHES.other;
}

export function categorize(note) {
  if ([35, 36].includes(note)) return "kick";
  if ([37, 38, 39, 40].includes(note)) return "snare";
  if ([41, 43, 45, 47, 48, 50, 60, 61, 62, 63, 64, 65, 66].includes(note))
    return "tom";
  if ([42, 44, 46].includes(note)) return "hihat";
  if ([49, 51, 52, 55, 57, 59].includes(note)) return "cymbal";
  return "click";
}

export function autoZoneForNote(note) {
  if (AUTO_ZONE_BY_NOTE.has(note)) return AUTO_ZONE_BY_NOTE.get(note);
  const type = categorize(note);
  if (type === "kick") return "bass";
  if (type === "snare") return "tom3";
  if (type === "tom") return "tom3";
  return "cymbalRod";
}

export function noteLabel(note) {
  return GM_NAME_BY_NOTE.get(note) || `Percussion ${note}`;
}

export function instrumentLabel(program) {
  const raw = GM_INSTRUMENT_NAMES[program] || `Program ${program}`;
  return raw
    .split("_")
    .map((word) => word.charAt(0).toUpperCase() + word.slice(1))
    .join(" ");
}
